# Generated by Django 4.2.7 on 2025-10-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('price_per_kwh', models.FloatField(default=0.8, verbose_name='Cena za kWh [PLN]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dom',
                'verbose_name_plural': 'Domy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID czujnika')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.house')),
            ],
            options={
                'verbose_name': 'Czujnik',
                'verbose_name_plural': 'Czujniki',
                'ordering': ['house', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Czas pomiaru')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Napięcie [V]')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Prąd [A]')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='Moc czynna [W]')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Energia [kWh]')),
                ('frequency', models.FloatField(blank=True, null=True, verbose_name='Częstotliwość [Hz]')),
                ('pf', models.FloatField(blank=True, null=True, verbose_name='Współczynnik mocy')),
                ('reactive_power', models.FloatField(blank=True, help_text='Obliczona na podstawie mocy czynnej i współczynnika mocy', null=True, verbose_name='Moc bierna [VAR]')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__561443_idx'), models.Index(fields=['timestamp'], name='sensors_sen_timesta_a94ae6_idx')],
            },
        ),
    ]
