# Generated by Django 5.2.7 on 2025-11-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='offline_threshold_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Po ilu sekundach bez pomiaru uznać czujnik za offline (np. 30)', verbose_name='Próg offline [s]'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='voltage_max_threshold',
            field=models.FloatField(blank=True, help_text='Alert gdy napięcie wzrośnie powyżej tej wartości', null=True, verbose_name='Max. napięcie [V]'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='voltage_min_threshold',
            field=models.FloatField(blank=True, help_text='Alert gdy napięcie spadnie poniżej tej wartości', null=True, verbose_name='Min. napięcie [V]'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('power_high', 'Przekroczono próg mocy'), ('voltage_anomaly', 'Anomalia napięcia'), ('monthly_limit', 'Przekroczono limit miesięczny'), ('sensor_offline', 'Czujnik offline'), ('sensor_online', 'Czujnik znów online'), ('anomaly', 'Inna anomalia')], max_length=20, verbose_name='Typ alertu'),
        ),
    ]
