# Generated by Django 4.2.20 on 2025-03-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='signature',
        ),
    ]
