# Generated by Django 5.2.7 on 2025-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_offline_threshold_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='current_max_threshold',
            field=models.FloatField(blank=True, help_text='Alert gdy prąd (natężenie) wzrośnie powyżej tej wartości', null=True, verbose_name='Max. prąd [A]'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('power_high', 'Przekroczono próg mocy'), ('voltage_anomaly', 'Anomalia napięcia'), ('current_high', 'Przekroczono próg prądu'), ('monthly_limit', 'Przekroczono limit miesięczny'), ('sensor_offline', 'Czujnik offline'), ('sensor_online', 'Czujnik znów online'), ('anomaly', 'Inna anomalia')], max_length=20, verbose_name='Typ alertu'),
        ),
    ]
