# Generated by Django 5.2.7 on 2025-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_current_max_threshold_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('power_high', 'Przekroczono próg mocy'), ('current_high', 'Przekroczono próg prądu'), ('voltage_anomaly', 'Anomalia napięcia'), ('monthly_limit', 'Przekroczono limit miesięczny'), ('sensor_offline', 'Czujnik offline'), ('sensor_online', 'Czujnik znów online'), ('anomaly', 'Inna anomalia')], max_length=20, verbose_name='Typ alertu'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='current_max_threshold',
            field=models.FloatField(blank=True, help_text='Alert gdy prąd (natężenie) wzrośnie powyżej tej wartości (np. 10)', null=True, verbose_name='Max. prąd [A]'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='offline_threshold_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Po ilu sekundach bez pomiaru uznać czujnik za offline (np. 30)', verbose_name='Próg offline [s]'),
        ),
    ]
